# Generated by Django 5.2.11 on 2026-02-15 10:00

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='magazine/coverImage/', verbose_name='Cover Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Issued At')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='magazine/pdf/', verbose_name='PDF')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Page Count')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Magazine',
                'verbose_name_plural': 'Magazine',
            },
        ),
    ]
