# Generated by Django 5.2.11 on 2026-02-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazine',
            options={'ordering': ['-issued_at', '-created_at'], 'verbose_name': 'Magazine', 'verbose_name_plural': 'Magazine'},
        ),
        migrations.AddField(
            model_name='magazine',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured on Homepage'),
        ),
    ]
