# Generated by Django 5.2.11 on 2026-02-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_alter_magazine_options_magazine_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visits',
                'ordering': ['-visited_at'],
            },
        ),
    ]
