# Generated by Django 5.2.11 on 2026-02-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
    ]
